import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import DropdownMenu from "../components/DropdownMenu";
import Header from "../components/Header";
import HomePageMain from "../components/HomePageMain";
import styles from "../styles/Home.module.css";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <DropdownMenu/>
      <HomePageMain />
    </>
  );
}
